DIFFXPY_TREAT_ZEROVAR_TT_AS_SIG = True

BATCHGLM_OPTIM_GD = False
BATCHGLM_OPTIM_ADAM = False
BATCHGLM_OPTIM_ADAGRAD = False
BATCHGLM_OPTIM_RMSPROP = False
BATCHGLM_OPTIM_NEWTON = False
BATCHGLM_OPTIM_NEWTON_TR = True
BATCHGLM_OPTIM_IRLS = False
BATCHGLM_OPTIM_IRLS_GD = False
BATCHGLM_OPTIM_IRLS_TR = False
BATCHGLM_OPTIM_IRLS_GD_TR = False
BATCHGLM_PROVIDE_BATCHED = False
BATCHGLM_TERMINATION_TYPE = "global"