BATCHGLM_OPTIM_GD = False
BATCHGLM_OPTIM_ADAM = False
BATCHGLM_OPTIM_ADAGRAD = False
BATCHGLM_OPTIM_RMSPROP = False
BATCHGLM_OPTIM_NEWTON = False
BATCHGLM_OPTIM_NEWTON_TR = False
BATCHGLM_OPTIM_IRLS = False
BATCHGLM_OPTIM_IRLS_GD = False
BATCHGLM_OPTIM_IRLS_TR = True
BATCHGLM_OPTIM_IRLS_GD_TR = True

BATCHGLM_PROVIDE_BATCHED = True
BATCHGLM_PROVIDE_FIM = True
BATCHGLM_PROVIDE_HESSIAN = False

BATCHGLM_BACKEND = "tf1"
BATCHGLM_FEATUREWISE = True
BATCHGLM_AUTOGRAD = True
