BATCHGLM_OPTIM_GD = True
BATCHGLM_OPTIM_ADAM = True
BATCHGLM_OPTIM_ADAGRAD = False
BATCHGLM_OPTIM_RMSPROP = False
BATCHGLM_OPTIM_NEWTON = True
BATCHGLM_OPTIM_IRLS = True
BATCHGLM_TERMINATION_TYPE = "by_feature"