from diffxpy.testing.base import two_sample
from diffxpy.testing.base import lrt
from diffxpy.testing.base import wald
from diffxpy.testing.base import t_test
from diffxpy.testing.base import rank_test
from diffxpy.testing.base import partition
from diffxpy.testing.base import pairwise
from diffxpy.testing.base import versus_rest
from diffxpy.testing.base import continuous_1d
from diffxpy.testing.base import design_matrix
from diffxpy.testing.base import coef_names
